# Generated by Django 2.2.4 on 2019-09-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='radio',
            field=models.IntegerField(default=100),
        ),
    ]
