# Generated by Django 2.2.4 on 2019-10-23 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_touristpoint_radio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'usuario y ruta',
                'verbose_name_plural': 'usuarios y rutas',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'ciudad', 'verbose_name_plural': 'ciudades'},
        ),
        migrations.AlterModelOptions(
            name='prize',
            options={'verbose_name': 'premio', 'verbose_name_plural': 'premios'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'restaurante', 'verbose_name_plural': 'restaurantes'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'rol', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'ruta', 'verbose_name_plural': 'rutas'},
        ),
        migrations.AlterModelOptions(
            name='touristpoint',
            options={'verbose_name': 'punto turistico', 'verbose_name_plural': 'puntos turisticos'},
        ),
        migrations.AlterModelOptions(
            name='touristpointroute',
            options={'verbose_name': 'punto turistico y ruta', 'verbose_name_plural': 'puntos turisticos y rutas'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'usuario y rol', 'verbose_name_plural': 'usuarios y roles'},
        ),
        migrations.AlterField(
            model_name='route',
            name='users',
            field=models.ManyToManyField(through='myapp.UserRoute', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.Route'),
        ),
        migrations.AddField(
            model_name='userroute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
